#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         libnet
version:      1.18
version_from: 
installdirs:  perl
requires:
    IO::Socket:                    1.05
    Socket:                        1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
